/***********************************************************************
* FILENAME :    mousewheeleatereventfilter.c
*
* DESCRIPTION :
*       This object is an event filter to disable mouse scroll wheel interactions.
*
* NOTES :
*       Some QWidgets have scroll wheel interactions which cannot be disabled.
*
* AUTHOR :  Matthew R. Miller       START DATE :    March 6, 2018
*
* CHANGES : N/A - N/A
*
* VERSION       DATE            WHO                     DETAIL
* 0.1           March 6, 2018      Matthew R. Miller       Initial Rev
*
************************************************************************/
#include "mousewheeleatereventfilter.h"
#include <QEvent>

//Autogenerated constructor
MouseWheelEaterEventFilter::MouseWheelEaterEventFilter(QObject *parent) : QObject(parent)
{

}

//If the event is a mouse scroll wheel event, eventFilter returns true to disable further processing
bool MouseWheelEaterEventFilter::eventFilter(QObject *watched, QEvent *event)
{
    if(event->type() == QEvent::Wheel)
        return true;
    return false;
}
